/**
 * DSH Desktop self-updater — checks the official repository baseline and
 * applies updates in one click.
 *
 * Baseline sources, tried in order:
 *   1. `website/download/latest.yml` committed to the official repository
 *      main branch (auto-generated by `pnpm dist:win`). It carries version +
 *      sha512 + size and is the canonical "official baseline" — the updater
 *      aligns to exactly what the official build produced.
 *   2. GitHub Releases (`releases/latest`) as a fallback for repos that
 *      publish releases without committing the download folder.
 *
 * Update mechanics: download `dsh-desktop-setup-x64.exe`, verify its sha512
 * against the manifest, then launch it with the user's normal token — exactly
 * like opening the installer manually. The user walks the standard three-step
 * install flow (choose directory → install → launch); the installer itself
 * asks whether to close a running DSH Desktop when the target directory is in
 * use, so the app never quits or overlays itself in the background.
 *
 * For local testing the manifest URL can be overridden with the
 * `DSH_DESKTOP_UPDATE_MANIFEST` env var (a full latest.yml URL; the download
 * URL inside it is resolved against it).
 */
import { app, ipcMain, shell } from 'electron'
import { createHash, randomUUID } from 'node:crypto'
import { createWriteStream } from 'node:fs'
import { mkdir, rename, rm } from 'node:fs/promises'
import { Readable, Transform } from 'node:stream'
import { pipeline } from 'node:stream/promises'
import path from 'node:path'
import { spawn } from 'node:child_process'

export const OFFICIAL_REPO = 'oykb58246/dsh-desktop'
export const OFFICIAL_REPO_URL = `https://github.com/${OFFICIAL_REPO}`
export const SETUP_ARTIFACT = 'dsh-desktop-setup-x64.exe'

const RAW_BASE = `https://raw.githubusercontent.com/${OFFICIAL_REPO}/main`
const DEFAULT_MANIFEST_URL = `${RAW_BASE}/website/download/latest.yml`
const MANIFEST_URL = process.env.DSH_DESKTOP_UPDATE_MANIFEST || DEFAULT_MANIFEST_URL
const API_BASE = `https://api.github.com/repos/${OFFICIAL_REPO}`
const NPM_LATEST_URL = 'https://registry.npmjs.org/@deepseek-ai%2Fdsh/latest'
const USER_AGENT = 'dsh-desktop-updater'
// The setup artifact is small; a download that makes no progress for this long
// is stuck (server stalled, connection half-open) and must not leave the tools
// panel in the "下载中" state forever.
const DOWNLOAD_TIMEOUT_MS = 20 * 60_000

const state = {
  latest: null, // manifest snapshot or null when no baseline was published
  checkedAt: null,
  checkError: null,
  downloaded: null, // { path, size, sha512Ok, ready }
  downloadError: null,
  downloading: false,
  abort: null,
  kernelLatest: null,
}

let options = null

function errorMessage(error) {
  return error instanceof Error ? error.message : String(error)
}

async function fetchText(url, timeoutMs) {
  const response = await fetch(url, {
    headers: { 'user-agent': USER_AGENT },
    redirect: 'follow',
    signal: AbortSignal.timeout(timeoutMs),
  })
  if (!response.ok) {
    const error = new Error(`HTTP ${response.status}`)
    error.status = response.status
    throw error
  }
  return await response.text()
}

async function fetchJson(url, extraHeaders, timeoutMs) {
  const response = await fetch(url, {
    headers: { 'user-agent': USER_AGENT, ...extraHeaders },
    redirect: 'follow',
    signal: AbortSignal.timeout(timeoutMs),
  })
  if (!response.ok) {
    const error = new Error(`HTTP ${response.status}`)
    error.status = response.status
    throw error
  }
  return await response.json()
}

/** Minimal parser for the electron-builder `latest.yml` subset we consume. */
function parseLatestYml(text) {
  const clean = String(text).replace(/^\uFEFF/, '')
  const grab = (regex) => {
    const match = regex.exec(clean)
    return match === null ? null : match[1].trim()
  }
  const version = grab(/^version:\s*([^\s#]+)/m)
  if (version === null) return null
  const fileUrl = grab(/^\s*-\s*url:\s*(\S+)/m) ?? grab(/^url:\s*(\S+)/m) ?? SETUP_ARTIFACT
  const sha512 = grab(/^\s*sha512:\s*(\S+)/m)
  const size = grab(/^\s*size:\s*(\d+)/m)
  const releaseDate = grab(/^releaseDate:\s*'?([^'\r\n]+)'?/m)
  return {
    version,
    fileUrl,
    sha512,
    size: size === null ? null : Number(size),
    releaseDate: releaseDate === null ? null : releaseDate,
  }
}

/**
 * Resolve the official baseline. Returns null when the official repo has not
 * published a baseline yet; throws when the update sources are unreachable.
 */
async function fetchManifest() {
  const misses = []
  let networkError = null

  // 1. Committed build baseline (canonical; carries sha512 for verification).
  try {
    const text = await fetchText(MANIFEST_URL, 20_000)
    const parsed = parseLatestYml(text)
    if (parsed !== null) {
      return {
        version: parsed.version,
        releaseDate: parsed.releaseDate,
        size: parsed.size,
        sha512: parsed.sha512,
        url: new URL(parsed.fileUrl, MANIFEST_URL).href,
        source: 'repo-latest-yml',
        sourceLabel: '官方仓库 latest.yml',
      }
    }
    misses.push('官方仓库 latest.yml 缺少 version 字段')
  } catch (cause) {
    if (cause?.status === 404) misses.push('官方仓库尚无 latest.yml')
    else networkError = cause
  }

  // 2. GitHub Releases (fallback; assets there carry no sha512).
  try {
    const json = await fetchJson(`${API_BASE}/releases/latest`, { accept: 'application/vnd.github+json' }, 20_000)
    const version = String(json?.tag_name ?? '').replace(/^v/i, '')
    const assets = Array.isArray(json?.assets) ? json.assets : []
    const asset = assets.find((a) => typeof a?.name === 'string' && a.name === SETUP_ARTIFACT)
      ?? assets.find((a) => typeof a?.name === 'string' && /setup.*\.exe$/i.test(a.name))
      ?? assets.find((a) => typeof a?.name === 'string' && a.name.endsWith('.exe'))
    if (version !== '' && typeof asset?.browser_download_url === 'string') {
      return {
        version,
        releaseDate: json?.published_at ?? null,
        size: typeof asset.size === 'number' ? asset.size : null,
        sha512: null,
        url: asset.browser_download_url,
        source: 'github-release',
        sourceLabel: `GitHub Release ${json?.tag_name ?? version}`,
      }
    }
    misses.push('官方仓库尚未发布 Release 资产')
  } catch (cause) {
    if (cause?.status === 404) misses.push('官方仓库尚无 Release')
    else if (networkError === null) networkError = cause
  }

  if (networkError !== null) {
    throw new Error(`更新源不可达：${errorMessage(networkError)}（${misses.join('；')}）`)
  }
  return null
}

/** Compare two dotted version strings numerically (ignores a leading `v`). */
export function compareVersions(a, b) {
  const norm = (value) => String(value).trim().replace(/^v/i, '')
  const left = norm(a).split(/[.-]/)
  const right = norm(b).split(/[.-]/)
  const length = Math.max(left.length, right.length)
  for (let index = 0; index < length; index += 1) {
    const x = left[index] ?? ''
    const y = right[index] ?? ''
    const nx = /^\d+$/.test(x) ? Number.parseInt(x, 10) : null
    const ny = /^\d+$/.test(y) ? Number.parseInt(y, 10) : null
    if (nx !== null && ny !== null) {
      if (nx !== ny) return nx < ny ? -1 : 1
    } else if (x !== y) {
      return x < y ? -1 : 1
    }
  }
  return 0
}

function sendProgress(payload) {
  options?.sendProgress?.(payload)
}

function snapshot() {
  const current = options?.version ?? app.getVersion()
  const latest = state.latest
  const downloaded = state.downloaded
  const installed = options?.installed?.() ?? false
  return {
    current,
    repo: OFFICIAL_REPO,
    repoUrl: OFFICIAL_REPO_URL,
    installed,
    installDir: installed ? options?.installDir?.() ?? null : null,
    latest: latest === null
      ? null
      : {
          version: latest.version,
          releaseDate: latest.releaseDate,
          size: latest.size,
          sha512: latest.sha512,
          url: latest.url,
          source: latest.source,
          sourceLabel: latest.sourceLabel,
        },
    updateAvailable: latest !== null && compareVersions(latest.version, current) > 0,
    checkedAt: state.checkedAt,
    error: state.checkError,
    downloading: state.downloading,
    downloadError: state.downloadError,
    downloaded: downloaded === null
      ? null
      : { size: downloaded.size, sha512Ok: downloaded.sha512Ok, ready: downloaded.ready },
    kernel: { bundled: options?.kernelBundled?.() ?? null, latest: state.kernelLatest },
  }
}

/** Run a full check against the official baseline and the kernel registry. */
export async function checkForUpdates() {
  state.checkedAt = new Date().toISOString()
  state.checkError = null
  try {
    state.latest = await fetchManifest()
  } catch (error) {
    state.checkError = errorMessage(error)
    state.latest = null
  }
  try {
    const json = await fetchJson(NPM_LATEST_URL, {}, 15_000)
    state.kernelLatest = typeof json?.version === 'string' ? json.version : null
  } catch {
    state.kernelLatest = null // informational only; never blocks the check
  }
  return snapshot()
}

/** Background check for the boot badge; never throws. */
export async function runBackgroundCheck() {
  try {
    await checkForUpdates()
  } catch {
    // The snapshot still carries the failure; boot must never break.
  }
  return snapshot()
}

/** Download the baseline artifact with progress + sha512 verification. */
export async function downloadUpdate() {
  if (state.downloading) return snapshot()
  if (state.downloaded?.ready) return snapshot()
  if (state.latest === null) {
    throw new Error(state.checkError ?? '没有可用的官方基线版本')
  }
  const latest = state.latest
  const updatesDir = path.join(app.getPath('userData'), 'updates')
  await mkdir(updatesDir, { recursive: true })
  const target = path.join(updatesDir, SETUP_ARTIFACT)
  const partial = `${target}.${randomUUID()}.part`

  state.downloading = true
  state.downloadError = null
  const controller = new AbortController()
  state.abort = controller
  // The user can cancel via `controller`; the timeout guards against a
  // half-open connection that would otherwise hang the download forever.
  const downloadSignal = AbortSignal.any([
    controller.signal,
    AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS),
  ])

  try {
    const response = await fetch(latest.url, {
      headers: { 'user-agent': USER_AGENT },
      redirect: 'follow',
      signal: downloadSignal,
    })
    if (!response.ok || response.body === null) throw new Error(`HTTP ${response.status}`)
    const total = Number(response.headers.get('content-length') ?? latest.size ?? 0)
    let received = 0
    let lastPercent = -1
    const hash = createHash('sha512')
    const meter = new Transform({
      transform(chunk, _encoding, callback) {
        received += chunk.length
        hash.update(chunk)
        const percent = total > 0 ? Math.floor((received * 100) / total) : -1
        if (percent !== lastPercent) {
          lastPercent = percent
          sendProgress({ phase: 'download', received, total, percent: percent >= 0 ? percent : null })
        }
        callback(null, chunk)
      },
    })
    sendProgress({ phase: 'download', received: 0, total, percent: 0 })
    await pipeline(Readable.fromWeb(response.body), meter, createWriteStream(partial), {
      signal: downloadSignal,
    })

    const digest = hash.digest('base64')
    const sha512Ok = latest.sha512 !== null ? digest === latest.sha512 : null
    const sizeOk = latest.size !== null && Number.isFinite(latest.size) ? received === latest.size : true
    sendProgress({ phase: 'verify', received, total: received, percent: 100, sha512Ok, sizeOk })
    if (sha512Ok === false || !sizeOk) {
      state.downloadError = sha512Ok === false
        ? 'sha512 校验失败：下载文件与官方基线不一致'
        : '下载大小与官方基线不一致'
      state.downloaded = null
      await rm(partial, { force: true })
      state.downloading = false
      return snapshot()
    }

    await rename(partial, target)
    state.downloaded = { path: target, size: received, sha512Ok, ready: true }
    state.downloading = false
    return snapshot()
  } catch (error) {
    if (!controller.signal.aborted) {
      state.downloadError = downloadSignal.aborted && !controller.signal.aborted
        ? `下载超时（超过 ${Math.round(DOWNLOAD_TIMEOUT_MS / 60_000)} 分钟无进展），已取消下载`
        : errorMessage(error)
    }
    await rm(partial, { force: true }).catch(() => {})
    state.downloading = false
    return snapshot()
  }
}

export function cancelDownload() {
  if (state.downloading && state.abort !== null) state.abort.abort()
  state.downloading = false
  return snapshot()
}

/**
 * Launch the downloaded installer for the user — no overlay, no auto-relaunch,
 * no forced quit. The user walks the exact same flow as a fresh install:
 * choose the directory (prefilled from the previous install), click 安装
 * (only then does the installer elevate), and optionally launch the app on
 * the completion page. If the target directory is in use, the installer's
 * process detection asks to close the running DSH Desktop.
 */
export async function applyUpdate() {
  const downloaded = state.downloaded
  if (downloaded === null || downloaded.ready !== true) {
    throw new Error('尚未下载可用的更新包')
  }
  if (downloaded.sha512Ok === false) {
    throw new Error('更新包未通过校验，请重新下载')
  }
  // Start non-elevated with the user's token, like a double-click on the
  // installer; the installer elevates itself when 安装 is clicked.
  await new Promise((resolve, reject) => {
    const child = spawn(downloaded.path, [], { detached: true, stdio: 'ignore', windowsHide: true })
    child.once('error', reject)
    child.once('spawn', () => {
      child.unref()
      resolve()
    })
  })
  return { ok: true }
}

/** Register the updater IPC surface for the tools window + preload bridge. */
export function registerUpdateIpc(registerOptions) {
  options = registerOptions
  ipcMain.handle('update:info', () => snapshot())
  ipcMain.handle('update:check', () => checkForUpdates())
  ipcMain.handle('update:download', () => downloadUpdate())
  ipcMain.handle('update:cancel', () => cancelDownload())
  ipcMain.handle('update:apply', () => applyUpdate())
  ipcMain.handle('update:open-repo', () => {
    void shell.openExternal(OFFICIAL_REPO_URL)
    return { ok: true }
  })
}
